name: Blog Post
on:
  schedule:     # Runs every 500 minutes
    - cron: '*/500 * * * *'
  workflow_dispatch:

  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://zapier.com/engine/rss/73497/Courtneyr-dev"
          max_post_count: 25

- name: Metrics embed
  uses: lowlighter/metrics@v3.28
